# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kirrurl',
            old_name='tiemstamp',
            new_name='timestamp',
        ),
    ]
